name: proper_filesize
description: a self-contained dart library that converts bytes to human readable file sizes and backwards. Supports binary and metric units.
version: 1.0.0
homepage: https://github.com/joaquimguimaraes/proper_filesize

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^1.0.1
dependencies: 
