name: proper_filesize
description: Easily convert and format file sizes in your Dart applications. This library handles bytes, metric/binary units, and provides human-readable output for user interfaces, data processing, and more.
version: 1.0.0
homepage: https://github.com/gilnobrega/proper_filesize

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
