name: proper_filesize
description: >-
  A versatile Dart library for converting between bytes and human-readable file
  sizes (e.g., "1.2 KB", "3.5 MB", "1.5 GiB") with support for both binary
  (KiB, MiB, GiB) and metric (KB, MB, GB) units, customizable decimal
  precision, and long format types (e.g., "KB" vs "kilobyte").
version: 1.0.0
homepage: https://github.com/gilnobrega/proper_filesize

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
