name: proper_filesize
description: Standalone file size conversion and formatting library. Generate human-readable output for UIs. Supports metric/binary units (KB, KiB, MB, MiB, etc.)
version: 1.0.2
homepage: https://github.com/gilnobrega/proper_filesize

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
